- name: Prepare ansible cache
  hosts: 
   - tracker
   - seeder
   - peer
  sudo: yes
  roles:
    - admin/prepare

- name: Install bittorrent-tracker
  hosts: 
   - tracker
  sudo: yes
  roles:
    - admin/deploy_bittorrent-tracker

- name: Install pigz
  hosts: 
   - tracker
   - seeder
   - peer
  sudo: yes
  roles:
    - admin/pigz

- name: Install screen
  hosts: 
   - tracker
   - seeder
  sudo: yes
  roles:
    - admin/screen

