# If the Bittorrent tracker is running, this will kill the process. Note that if it is not running you will receive an error.
- name: stop tracker
  shell: pkill -f 'SCREEN.*bittorrent-tracker*'
  register: result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc not in [0, 1]
  tags: stop_tracker


